<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" />
    <PackageReference Include="HotAvalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TagTag\TagTag.csproj" />
  </ItemGroup>
</Project>
